import { Sparkles, X } from "lucide-react";

interface AIInsightPanelProps {
  insight: string | null;
  onClose: () => void;
}

const AIInsightPanel = ({ insight, onClose }: AIInsightPanelProps) => {
  if (!insight) return null;

  return (
    <div className="w-80 glass rounded-2xl p-6 animate-slide-in">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles size={16} className="text-secondary" />
          <h3 className="font-semibold text-foreground text-sm">AI Insight</h3>
        </div>
        <button onClick={onClose} className="text-muted-foreground hover:text-foreground transition-colors">
          <X size={16} />
        </button>
      </div>
      <p className="text-sm text-muted-foreground leading-relaxed">{insight}</p>
      <div className="mt-4 pt-4 border-t border-border/30">
        <p className="text-xs text-muted-foreground/60">Generated by MeetWise AI</p>
      </div>
    </div>
  );
};

export default AIInsightPanel;
